# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Desktop/op_sys/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Desktop/op_sys/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Desktop/op_sys/project/CMakeFiles /home/user/Desktop/op_sys/project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Desktop/op_sys/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named filedistance

# Build rule for target.
filedistance: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 filedistance
.PHONY : filedistance

# fast build rule for target.
filedistance/fast:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/build
.PHONY : filedistance/fast

changefile.o: changefile.c.o

.PHONY : changefile.o

# target to build an object file
changefile.c.o:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/changefile.c.o
.PHONY : changefile.c.o

changefile.i: changefile.c.i

.PHONY : changefile.i

# target to preprocess a source file
changefile.c.i:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/changefile.c.i
.PHONY : changefile.c.i

changefile.s: changefile.c.s

.PHONY : changefile.s

# target to generate assembly for a file
changefile.c.s:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/changefile.c.s
.PHONY : changefile.c.s

computedistance.o: computedistance.c.o

.PHONY : computedistance.o

# target to build an object file
computedistance.c.o:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/computedistance.c.o
.PHONY : computedistance.c.o

computedistance.i: computedistance.c.i

.PHONY : computedistance.i

# target to preprocess a source file
computedistance.c.i:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/computedistance.c.i
.PHONY : computedistance.c.i

computedistance.s: computedistance.c.s

.PHONY : computedistance.s

# target to generate assembly for a file
computedistance.c.s:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/computedistance.c.s
.PHONY : computedistance.c.s

directoryscan.o: directoryscan.c.o

.PHONY : directoryscan.o

# target to build an object file
directoryscan.c.o:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/directoryscan.c.o
.PHONY : directoryscan.c.o

directoryscan.i: directoryscan.c.i

.PHONY : directoryscan.i

# target to preprocess a source file
directoryscan.c.i:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/directoryscan.c.i
.PHONY : directoryscan.c.i

directoryscan.s: directoryscan.c.s

.PHONY : directoryscan.s

# target to generate assembly for a file
directoryscan.c.s:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/directoryscan.c.s
.PHONY : directoryscan.c.s

filereader.o: filereader.c.o

.PHONY : filereader.o

# target to build an object file
filereader.c.o:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/filereader.c.o
.PHONY : filereader.c.o

filereader.i: filereader.c.i

.PHONY : filereader.i

# target to preprocess a source file
filereader.c.i:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/filereader.c.i
.PHONY : filereader.c.i

filereader.s: filereader.c.s

.PHONY : filereader.s

# target to generate assembly for a file
filereader.c.s:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/filereader.c.s
.PHONY : filereader.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/filedistance.dir/build.make CMakeFiles/filedistance.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... filedistance"
	@echo "... changefile.o"
	@echo "... changefile.i"
	@echo "... changefile.s"
	@echo "... computedistance.o"
	@echo "... computedistance.i"
	@echo "... computedistance.s"
	@echo "... directoryscan.o"
	@echo "... directoryscan.i"
	@echo "... directoryscan.s"
	@echo "... filereader.o"
	@echo "... filereader.i"
	@echo "... filereader.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

